### ISSUE TITLE
程序开起来，什么都不做，关闭的时候appcontext.cs  line84 报错

### ISSUE THREAD

**Issue by xiaoweige123** [Monika1313/Wu.CommTool#5]
程序开起来，什么都不做，关闭的时候appcontext.cs  line
![1718175271565](https://github.com/Monika1313/Wu.CommTool/assets/64315659/5f571771-dfb5-42ed-a5b5-0b3900b637b1)
84 报错
![1718175271565](https://github.com/Monika1313/Wu.CommTool/assets/64315659/ccdeee76-2ed2-4f6b-bb10-d65033305175)

**Comment by Monika1313** [comment]
更新VS既可解决
